### ISSUE TITLE
Can't add more than 9 games

### ISSUE THREAD

**Issue by Ev0-BH** [pathartl/BleemSync#10]
If you try to add more than 9 games, you get this error:

Unhandled Exception: System.Exception: Your games directory structure is invalid. Make sure that folders are named as a whole number (e.g. 1, 2, 3) and there are no gaps in the sequence
   at BleemSync.Utilities.Filesystem.GetGameIds() in C:\Users\Pat\source\repos\BleemSync\BleemSync.Utilities\Filesystem.cs:line 51
   at BleemSync.Program.Main(String[] args) in C:\Users\Pat\source\repos\BleemSync\BleemSync\Program.cs:line 18

As it reads 1, 10, 11, 12, 13, 2 etc etc

Renaming folder 01, 02, 03 etc does not work

**Comment by vecst** [comment]
I don't have a classic, if I did I would test this. What is you started at 100?

**Comment by pathartl** [comment]
Resolved in [0.3.0](https://github.com/pathartl/BleemSync/releases/tag/0.3.0)
