### ISSUE TITLE
The configuration file 'BleemSync.Config.json' was not found and is not optional. Linux

### ISSUE THREAD

**Issue by gavular** [pathartl/BleemSync#187]
Help I've seen the simlar post for this issue on Mac, but I still cannot get this to run in my linux terminal.  I am a newbie. What am i doing wrong / missing?

gavin@gavin-PC:~$ '/home/gavin/Downloads/BleemSync-0.4.1-linux-x64/BleemSync/BleemSync'

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'BleemSync.Config.json' was not found and is not optional. The physical path is '/home/gavin/BleemSync.Config.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at BleemSync.Program.Main(String[] args) in C:\data\repositories\BleemSync\BleemSync\Program.cs:line 20
Aborted

**Comment by GMMan** [comment]
Have you tried changing directoryto the BleemSync folder?

Duplicates #148
