### ISSUE TITLE
OSX Version looking for config in wrong place

### ISSUE THREAD

**Issue by ibaneye** [pathartl/BleemSync#73]
Looks for config file in my Users folder, instead of on the mounted thumbdrive from which BleemSync is run:
/Volumes/SONY/BleemSync/BleemSync ; exit;
Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'BleemSync.Config.json' was not found and is not optional. The physical path is '/Users/***/BleemSync.Config.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at BleemSync.Program.Main(String[] args) in C:\data\repositories\BleemSync\BleemSync\Program.cs:line 20
Abort trap: 6

**Comment by ibaneye** [comment]
That method does work.

**Comment by goophi** [comment]
I have the same issue? can you go into detail on how to fix?

**Comment by goophi** [comment]
after this is done I have the following screen:  

Added game [1] Bloody Roar 2 to the database
Added game [2] Capcom VS. SNK PRO to the database
Added game [3] Castlevania: Symphony of the Night to the database
Added game [4] Chrono Cross to the database
Added game [5] Crash Team Racing to the database
Added game [6] Diablo to the database
Added game [7] Dino Crisis 2 to the database
Added game [8] Resident Evil 2 to the database
Added game [9] Resident Evil 3 to the database
Added game [10] Street Fighter Alpha 3 to the database
Added game [11] Tony Hawk's Pro Skater 2 to the database
Added game [12] Crash Bandicoot 3: Warped to the database
Successfully inserted 12 games

after plugging it in I still have trouble seeing any new games loaded :(

**Comment by goophi** [comment]
this is my screen after clicking straight the bleemsync exe
Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'BleemSync.Config.json' was not found and is not optional. The physical path is '/Users/philipluu/BleemSync.Config.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at BleemSync.Program.Main(String[] args) in C:\data\repositories\BleemSync\BleemSync\Program.cs:line 20
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by goophi** [comment]
Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'BleemSync.Config.json' was not found and is not optional. The physical path is '/Users/myname/BleemSync.Config.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at BleemSync.Program.Main(String[] args) in C:\data\repositories\BleemSync\BleemSync\Program.cs:line 20
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by ibaneye** [comment]
@goophi 
Have you followed the formatting instructions? FAT32, SONY (uppercase). Do you know how to correctly format FAT32 on a Mac? MBR, not GUID.

**Comment by ibaneye** [comment]
I believe there is a list of supported thumb drives out there... I use Samsumg Bars with no issue. Currently using a 64GB one.

**Comment by GMMan** [comment]
Edited and pinned this issue instead of #148 because this contains a solution.
